apiVersion: v1
kind: Service
metadata:
  name: student-api-service
  labels:
    run: student-api
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: student-api-selector
  type: NodePort